language: node_js
node_js:
  - "8"

before_deploy:
  - yarn build

deploy:
  provider: s3
  bucket: order.demo1.microfrontendexample.com
  local_dir: build
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
